---
name: CI

'on': [push]

jobs:
  test:
    name: ${{ matrix.lisp }} with libgit2 ${{ matrix.libgit2 }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lisp: [sbcl-bin]
        libgit2: ['0.27', '0.28', '1.0', '1.1', '1.2', '1.3', '1.4', '1.5']
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - name: Test
        env:
          LIBGIT2: ${{ matrix.libgit2 }}
        run: earthly github.com/russell/cl-git:$GITHUB_SHA+test-libgit2-$LIBGIT2
